name: Instagram (Books)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      INSTAGRAM_APP_ID: ${{ secrets.INSTAGRAM_APP_ID }}
      INSTAGRAM_URL_GRAPH_API: ${{ secrets.INSTAGRAM_URL_GRAPH_API }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_URL_BOOKS: ${{ secrets.SUPABASE_URL_BOOKS }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install
    - run: npm run start-instagram
