name: Telegram (Books)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID_TO_NOTIFY: ${{ secrets.TELEGRAM_CHAT_ID_TO_NOTIFY }}
      TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
    - run: npm install
    - run: npm run start-telegram
